language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install:
    - pip install -U tox-travis
    - pip install coveralls
script: tox
after_success: coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    python: 3.7
    repo: zertrin/zkpytb
    tags: true
  username: zertrin
  password:
    secure: !!binary |
      RDRGaVZyZktldU9KSDBGUEhhbGFJOHp3WitBb2xUbTRJb2pzNFdmZXJkd1hDZDgwblFCZ0s5Mnl3
      eEh3RGczUVF5K0NCbGFYdmRYWGxpUjFkMWlLNWIwMVRPUm9qWDZRMjJLMlA1VkdReUV6YUxRdHRB
      U1RWbTY1YnpMQjVaSS9kS2F3MFV0a1BjOFNZMUxJdVVjcUxDaG5uaFlpQ0NjVlhDUDNwWWt4VTRu
      dnQydS9IT3Rad3ZrOEd5akFleUZUbHF6RTRwYjZxZll5UWJtaHRrZmpVeDgwd3YzZHd2c3hTNm9B
      QkpNc3N0aHFYMmh5NzByaERtTHVzb0NMMGt1bXV0aTFtZ3NmS2UxNmRnRVJreGxCSlB5VHdoRVRs
      WDBVRHlmNTRUVzRUZFBDN1JwRFdNVTViQ2RLMnN2cFV2UE5DbDBGYmd2RTB6OXNMOURhdld3TS9R
      ekhONEU4NFlGaTR4Z0J2ODhaTDM0L3dqQ3gxaXhZMDA5WWtQMUxiZHZITEtUWE9TOEVUTWNaSVkv
      cU50S1hnL0Z2VEs0NzRMVnFnalorYzJ4NE1nNHE2dDdzUXdobTlFdUFXTlhqWDl0VGI5Y1R0WjVv
      dy84dmpCWDlGVGduUUNSVnEzUE52N0ZSWDJvb094WDIwMFVlYms3QWZielB3cTB4bGo2cXF4NUF4
      RnF0dWhmMFcvWTZiUDdicVlYd3JtUUYyeXd0eTdCNjNDYUZEOFhMRzFYRWtrVG00anIxR0IvVDd0
      Y3FLdjdmZGdOd2UrbmZucUlLZ1RmRFBUNVBVOVJibng5ajVoK3hVL2U0ZTJGVWhaVnBkZDZReDhi
      UXpvMVVuOHM4OHdFVy9vaHNRV1IzWUxQSVNrT01LZzhna3BzZUV3Mk5iTE1jN3V0VXQ2Y0pDamM9
